steps:
  # Paso 1: Construir la imagen de Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/club-uleam', '.']
  
  # Paso 2: Subir la imagen a Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/club-uleam']
  
  # Paso 3: Desplegar automáticamente en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'club-uleam-service'
      - '--image=gcr.io/$PROJECT_ID/club-uleam'
      - '--region=us-central1'
      - '--allow-unauthenticated'
images:
  - 'gcr.io/$PROJECT_ID/club-uleam'