create table if not exists public.jugadores (
  id bigint generated by default as identity primary key,
  nombre text not null,
  posicion text not null,
  dorsal integer not null unique,
  created_at timestamp with time zone default now()
);

alter table public.jugadores enable row level security;

insert into public.jugadores (nombre, posicion, dorsal)
values
  ('Juan Perez', 'Portero', 1),
  ('Carlos Vera', 'Defensa', 4),
  ('Mauro Lucas', 'Mediocampista', 8)
on conflict (dorsal) do nothing;
